name: C/C++ CI

on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - 'include/**'
      - '.github/**'

  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  notification:
    runs-on: ubuntu-latest
    name: Notify start to IRC-gitlama
    outputs:
      branch: ${{ steps.extract_branch.outputs.branch }}
    steps:
      - name: Extract Branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: extract_branch
      - name: IRC notification
        uses: Gottox/irc-message-action@v2
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GitHub
          message: >
            ${{ github.actor }} started a build of
            ${{ github.event.repository.name }}
            [${{ steps.extract_branch.outputs.branch }}]
            "${{ github.event.head_commit.message }}"

  build:
    runs-on: ${{ matrix.os }}
    needs: notification
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
        compiler: [g++-12, clang++]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v4.1.1
      - name: Install Build Environment
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get install pkg-config autoconf-archive
             else
                brew upgrade
                brew install libtool
                brew install autoconf-archive
                brew install autoconf
                brew install automake
             fi
      - name: Install Dependencies
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                sudo apt-get install libicu-dev libxml2-dev libbz2-dev
                sudo apt-get install zlib1g-dev cppcheck
             else
                brew install libxml2
                brew install bzip2
                brew install zlib
                brew install cppcheck
             fi
      - name: Configure CppCheck
        run: |
             if [ "$RUNNER_OS" == "Linux" ]; then
                cpc_opts="--enable=warning,style --inline-suppr --force \
                          -I include -I /usr/local/include --quiet \
                          --std=c++17 --error-exitcode=0"
             else
                cpc_opts="--enable=warning,style --inline-suppr --force \
                          -I include --check-level=exhaustive --quiet \
                          --std=c++17 --error-exitcode=0"
             fi
             echo "cpc_opts=$cpc_opts" >> $GITHUB_ENV
      - name: install TiccUtils
        id: ticcutils
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          git clone https://github.com/LanguageMachines/ticcutils;
          cd ticcutils;
          bash bootstrap.sh;
          ./configure;
          make;
          sudo make install;
          cd ..;
        continue-on-error: true
      - name: get status ticcutils
        if: ${{ steps.ticcutils.outcome != 'success' }}
        run: echo "action_status=ticcutils" >> $GITHUB_ENV
      - name: install TiMBL
        if: ${{ env.action_status == '' }}
        id: timbl
        env:
          CXX: ${{ matrix.compiler }}
        run: |
          git clone https://github.com/LanguageMachines/timbl;
          cd timbl;
          bash bootstrap.sh;
          ./configure;
          make;
          sudo make install;
          cd ..;
        continue-on-error: true
      - name: get status timbl
        if: ${{ steps.timbl.outcome != 'success' }}
        run: echo "action_status=timbl" >> $GITHUB_ENV
      - name: compiler-id
        id: compiler
        run: |
          id=$(echo ${{matrix.compiler}} | cut -d\+ -f1)
          echo "id=$id" >> $GITHUB_OUTPUT
      - name: Static Code-check
        run: cppcheck ${{ env.cpc_opts }} .
      - name: bootstrap
        run: sh bootstrap.sh
      - name: configure
        if: ${{ env.action_status == '' }}
        id: configure
        env:
          CXX: ${{ matrix.compiler }}
        run: ./configure
        continue-on-error: true
      - name: get status configure
        if: ${{ env.action_status == '' && steps.configure.outcome != 'success' }}
        run: |
           echo "action_status=configure" >> $GITHUB_ENV
           [ -f config.log ] && cat config.log
      - name: make
        if: ${{ env.action_status == '' }}
        id: make
        run: make
        continue-on-error: true
      - name: get status make
        if: ${{ env.action_status == '' && steps.make.outcome != 'success' }}
        run: echo "action_status=make" >> $GITHUB_ENV
      - name: install
        id: install
        if: ${{ env.action_status == '' }}
        run: sudo make install
        continue-on-error: true
      - name: get status install
        if: ${{ env.action_status == '' && steps.install.outcome != 'success' }}
        run: echo "action_status=install" >> $GITHUB_ENV
      - name: Notify IRC of failure
        if: ${{ env.action_status != '' }}
        uses: Gottox/irc-message-action@v2
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GH-${{ runner.os }}-${{ steps.compiler.outputs.id }}
          message: "timblserver [${{ needs.notification.outputs.branch }}] build with ${{ matrix.compiler }} by ${{ github.actor }} on ${{ matrix.os }}: \u00034FAILED\u0003 in step ${{ env.action_status }}"
      - name: Notify IRC of succes
        if: ${{ env.action_status == '' }}
        uses: Gottox/irc-message-action@v2
        with:
          server: irc.uvt.nl
          channel: '#gitlama'
          nickname: GH-${{ runner.os }}-${{ steps.compiler.outputs.id }}
          message: "timblserver [${{ needs.notification.outputs.branch }}] build with ${{ matrix.compiler }} by ${{ github.actor }} on ${{ matrix.os }}: \u00033SUCCESS\u0003"
